# Generated by Django 6.0.1 on 2026-01-08 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="cantidad",
            new_name="stock",
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.CharField(default="General", max_length=50),
        ),
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(default="Sin descripción"),
        ),
        migrations.AddField(
            model_name="producto",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
